//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestureSign.CorePlugins.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestureSign.CorePlugins.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Language DisplayName=&quot;English&quot; Culture=&quot;en&quot; Version=&quot;6.1&quot;&gt;
        ///  &lt;CorePlugins&gt;
        ///    &lt;ActivateWindow&gt;
        ///      &lt;Name&gt;Activate Window&lt;/Name&gt;
        ///      &lt;Description&gt;Activate the specified window&lt;/Description&gt;
        ///      &lt;ClassName&gt;Window Class Name&lt;/ClassName&gt;
        ///      &lt;WindowTitle&gt;Window Title&lt;/WindowTitle&gt;
        ///      &lt;UsingRegularExpression&gt;Match as pattern&lt;/UsingRegularExpression&gt;
        ///      &lt;Timeout&gt;Wait for window to exist&lt;/Timeout&gt;
        ///      &lt;Millisecond&gt;milliseconds&lt;/Millisecond&gt;
        ///    &lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Language DisplayName=&quot;中文&quot; Culture=&quot;zh-CN&quot; Version=&quot;6.1&quot;&gt;
        ///  &lt;CorePlugins&gt;
        ///    &lt;ActivateWindow&gt;
        ///      &lt;Name&gt;激活窗口&lt;/Name&gt;
        ///      &lt;Description&gt;使指定窗口前置&lt;/Description&gt;
        ///      &lt;ClassName&gt;窗口类名&lt;/ClassName&gt;
        ///      &lt;WindowTitle&gt;窗口名&lt;/WindowTitle&gt;
        ///      &lt;UsingRegularExpression&gt;使用正则表达式&lt;/UsingRegularExpression&gt;
        ///      &lt;Timeout&gt;等待窗口时间&lt;/Timeout&gt;
        ///      &lt;Millisecond&gt;毫秒&lt;/Millisecond&gt;
        ///    &lt;/ActivateWindow&gt;
        ///    &lt;Delay&gt;
        ///      &lt;Name&gt;延时&lt;/Name&gt;
        ///      &lt;Description&gt;延迟 {0} 毫秒&lt;/Descriptio [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string zh {
            get {
                return ResourceManager.GetString("zh", resourceCulture);
            }
        }
    }
}
